# примеры API-запросов

@baseUrl = http://localhost:8000/api

# обновление списка
POST {{baseUrl}}/data/update/
Content-Type: application/json
Authorization: Token ca832e3b03cef70c8d3575947d46c529b394d2f3

{
  "url": "data.json"
}
###
# получение данных по id
GET {{baseUrl}}/hero/1
Content-Type: application/json
###
# поиск  по Name
GET {{baseUrl}}/search/A-Bomb
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
# hero
GET {{baseUrl}}/hero/1
Content-Type: application/json
Authorization: Token ca832e3b03cef70c8d3575947d46c529b394d2f3
###
# powerstats
GET {{baseUrl}}/powerstats/1
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
# appearance
GET {{baseUrl}}/appearance/1
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
# images
GET {{baseUrl}}/images/1
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
# biography
GET {{baseUrl}}/biography/1
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
# work
GET {{baseUrl}}/work/1
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
# connections
GET {{baseUrl}}/connections/1
Content-Type: application/json
Authorization: Token e04d284b57c9abedf7c4d7c81795d1aacd245521
###
