# Generated by Django 4.0.5 on 2022-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appearance_hero_id_alter_biography_hero_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='eyecolor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='haircolor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
